grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  #module_0:
    #class: LogisticRegression
    #module: sklearn.linear_model
    #params:
      #fit_intercept: true
    #search_param_grid:
      #fit_intercept:
      #- true
      #- false
      #penalty:
      #- l1
      #- l2
      #- elasticnet
      #- none
      #C:
      #- 0.001
      #- 0.01
      #- 0.1
      #- 1
      #- 10
      #- 100
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params::
      min_samples_leaf: 3
    search_param_grid:
      n_estimators:
      - 101
    #  - 201
    #  - 501
      criterion:
      - gini
    #  - entropy
      max_depth:
      - 60
      #- 80
      #- 100
      #- 110
      min_samples_split:
      #- 50
      #- 75
      - 100
     # - 200
      max_features:
      - sqrt
    #  - log2
      min_impurity_decrease:
      #- 0.000001
      - 0.00001
      #- 0.0001
      #- 0.001
    #  - 0.01
    #  - 0.0
      bootstrap:
      - true
    #  - false
      oob_score:
      - true
    #  - false
      ccp_alpha:
      - 0.000001
      #- 0.00001
      #- 0.0001
      #- 0.001
      #- 0.01
      #- 0.0