grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
      #penalty:
      #- l1
      #- l2
      #- elasticnet
      #- none
      C:
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10
      - 100
