columns:
  ID: int
  LIMIT_BAL: float
  SEX: category
  EDUCATION: category
  MARRIAGE: category
  AGE: int
  PAY_0: category
  PAY_2: category
  PAY_3: category
  PAY_4: category
  PAY_5: category
  PAY_6: category
  BILL_AMT1: float
  BILL_AMT2: float
  BILL_AMT3: float
  BILL_AMT4: float
  BILL_AMT5: float
  BILL_AMT6: float
  PAY_AMT1: float
  PAY_AMT2: float
  PAY_AMT3: float
  PAY_AMT4: float
  PAY_AMT5: float
  PAY_AMT6: float

columns_order:
  - ID
  - LIMIT_BAL
  - SEX
  - EDUCATION
  - MARRIAGE
  - AGE
  - PAY_0
  - PAY_2
  - PAY_3
  - PAY_4
  - PAY_5
  - PAY_6
  - BILL_AMT1
  - BILL_AMT2
  - BILL_AMT3
  - BILL_AMT4
  - BILL_AMT5
  - BILL_AMT6
  - PAY_AMT1
  - PAY_AMT2
  - PAY_AMT3
  - PAY_AMT4
  - PAY_AMT5
  - PAY_AMT6


target_column: default.payment.next.month

domain_value:
  SEX:
    - 1
    - 2
  EDUCATION:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  MARRIAGE:
    - 1
    - 2
    - 3
  PAY_0:
    - 0
    - -1 
    - 1 
    - -2
    - 2
    - 3
    - 4
    - 5
    - 8
    - 6
    - 7
  PAY_2:
  - 0
  - -1 
  - 1 
  - -2
  - 2
  - 3
  - 4
  - 5
  - 8
  - 6
  - 7
  PAY_3:
  - 0
  - -1 
  - 1 
  - -2
  - 2
  - 3
  - 4
  - 5
  - 8
  - 6
  - 7
  PAY_4:
  - 0
  - -1 
  - 1 
  - -2
  - 2
  - 3
  - 4
  - 5
  - 8
  - 6
  - 7
  PAY_5:
  - 0
  - -1 
  - 1 
  - -2
  - 2
  - 3
  - 4
  - 5
  - 8
  - 6
  - 7
  PAY_6:
  - 0
  - -1 
  - 1 
  - -2
  - 2
  - 3
  - 4
  - 5
  - 8
  - 6
  - 7

numerical_columns:
  - ID
  - LIMIT_BAL
  - AGE
  - BILL_AMT1
  - BILL_AMT2
  - BILL_AMT3
  - BILL_AMT4
  - BILL_AMT5
  - BILL_AMT6
  - PAY_AMT1
  - PAY_AMT2
  - PAY_AMT3
  - PAY_AMT4
  - PAY_AMT5
  - PAY_AMT6

categorical_columns:
  - SEX
  - EDUCATION
  - MARRIAGE
  - PAY_0
  - PAY_2
  - PAY_3
  - PAY_4
  - PAY_5
  - PAY_6